config/routes.rb
Rails.application.routes.draw do
    devise_for :users, :skip => :registration

    namespace :api do
        scope :v1 do
            mount_devise_token_auth_for 'User', at: 'auth'
        end
    end

    mount GrapeSwaggerRails::Engine, at: "/documentation"


    mount API::Base, at: "/"

    resources :cnaes
    post 'import_cnae' =>'cnaes#import', as: :import_cnae

    root to: 'cnaes#index'
    # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/cnae.rb
class Cnae < ApplicationRecord

    #method import txt frontend
    def self.import(file)
        begin 
            File.open(file.path).each do |line|
                dt_occurrence = line.slice(1..8)
                tm_occurrence = line.slice(42..48)

                cnae = Cnae.new

                cnae.tp_occurrence = line.slice(0)

                cnae.dt_occurrence = line.slice(1..8)

                tm_occurrence = line.slice(42..48)

            # verifica se data ok e add + 3 hrs
                begin
                    testedata = DateTime.parse(dt_occurrence + tm_occurrence, '%Y%m%d%H%M%S') + (3/24.0)
                    cnae.tm_occurrence = testedata.strftime('%H:%M:%S')
                    cnae.dt_occurrence = testedata.strftime('%Y-%m-%d')
                rescue
                    cnae.tm_occurrence = nil
                    cnae.dt_occurrence = nil
                end
                
                cnae.value = line.slice(9..18)
                
                # valor dividido por 100
                cnae.value = cnae.value / 100

                cnae.cpf = line.slice(19..29)

                cnae.card = line.slice(30..41)

                # salva apenas operações de débito e crédito
                if cnae.tp_occurrence == 1 || cnae.tp_occurrence == 4
                    cnae.save
                end
            end
            return true
        rescue => ex
            logger.error ex.message
            return ex.message
        end
    end



    #method import txt api
    def self.importfile(file)
        begin 
            cnaes = Array.new
            File.open(file).each do |line|
                dt_occurrence = line.slice(1..8)
                tm_occurrence = line.slice(42..48)

                cnae = Cnae.new

                cnae.tp_occurrence = line.slice(0)

                #cnae.dt_occurrence = line.slice(1..8)

                tm_occurrence = line.slice(42..48)

                # verifica se data ok e add + 3 hrs
                begin
                    testedata = DateTime.parse(dt_occurrence + tm_occurrence, '%Y%m%d%H%M%S') + (3/24.0)
                    cnae.tm_occurrence = testedata.strftime('%H:%M:%S')
                    cnae.dt_occurrence = testedata.strftime('%Y-%m-%d')

                rescue
                    cnae.tm_occurrence = nil
                    cnae.dt_occurrence = nil
                end
                
                cnae.value = line.slice(9..18)
                
                # valor dividido por 100
                cnae.value = cnae.value / 100

                cnae.cpf = line.slice(19..29)

                cnae.card = line.slice(30..41)

                # salva apenas operações de débito e crédito
                if cnae.tp_occurrence == 1 || cnae.tp_occurrence == 4
                    cnae.save 
                    cnaes.push(cnae)
                end

            end
            return cnaes
        rescue => ex
            logger.error ex.message
            return ex.message
        end
    end


end

app/controllers/api/v1/cnaes.rb
module API  
    module V1
        class Cnaes < Grape::API
            auth :grape_devise_token_auth, resource_class: :user
            #respond_to :json
            helpers GrapeDeviseTokenAuth::AuthHelpers

            include API::V1::Defaults

            resource :cnaes do
                desc "Return all cnaes", headers: {
                    "access-token" => {
                        description: "Valdates your identity",
                        required: true
                        },
                    "expiry" => {
                        description: "Validates your identety",
                        required: true
                        },
                    "type-token" => {
                        description: "Validates your identety",
                        required: true
                        },
                    "uid" => {
                        description: "Email login system",
                        required: true
                        },
                    "client" => {
                        description: "Validates your identety",
                        required: true
                        }
                    }
                get "", root: :cnaes do
                    authenticate_user!
                    cnaes = Cnae.all
                end

                desc "Import file Cnae format txt", headers: {
                    "access-token" => {
                        description: "Valdates your identity",
                        required: true
                        },
                    "expiry" => {
                        description: "Validates your identety",
                        required: true
                        },
                    "type-token" => {
                        description: "Validates your identety",
                        required: true
                        },
                    "uid" => {
                        description: "Email login system",
                        required: true
                        },
                    "client" => {
                        description: "Validates your identety",
                        required: true
                        },
                    "Content-Type" => {
                        description: "multpart/form-data",
                        required: true
                        }
                    }, 
                params: {
                    "cnae" => {
                        description: "Send file input",
                        required: true,
                        type: "File",
                        }
                    }
                post do
                    authenticate_user!
                    begin
                        Cnae.importfile(params[:cnae][:tempfile].path)
                    rescue
                        return {errors:[{messge: 'Arquivo não inserido.'}]}
                    end
                end

            end
        end
    end
end  

app/controllers/cnaes_controller.rb
class CnaesController < ApplicationController

    before_action :authenticate_user!


    def index
        @cnaes = Cnae.all
    end

    def import
        @result = Cnae.import(params[:file])
        if (@result == true)
            puts 'import'
            flash[:success] = 'Cnae importado com sucesso!'
            redirect_to cnaes_url 
        else
            if @result.index('Illegal')
                flash[:error] = 'Formato de arquivo deve ser .csv'
                redirect_to cnaes_url 
            else
                flash[:error] = @result
                redirect_to cnaes_url    
            end

        end
    end

end

app/helpers/cnaes_helper.rb
module CnaesHelper
end

app/views/cnaes/index.html.erb
<section class="content-header">
    <h1>
        <small>Upload Cnae</small>
    </h1>
    <ol class="breadcrumb">
        <li>
            <a href="#">
                <i class="class fa fa-dashboard"></i> Home</a>
        </li>
        <li class="active">
            <%#= link_to 'Ongs', ongs_path %>
        </li>
    </ol>
</section>
<section class="content">
    <div class="row">
        <div class="col-md-12">
            <div class="box box-success">

                <!-- Inline Form -->
                <div class="box-header with-border">
                    <h3 class="box-title">CNAES</h3>
                    <div class="pull-right">
                        <%#= link_to '<i class="ion ion-chatbubble-working"></i>'.html_safe, new_path(@ong.user.id), :style => 'font-size:18px', :title => 'Enviar Mensagem','data-toggle' => 'tooltip', 'data-placement' => 'left'  %>
                    </div>
                </div>
                <div class="box-body">
                    <div class="col-md-12">
                        <div class="row">


                            <div>
                                <h4>Importar Cnae &emsp;<a data-toggle="modal" data-target="#infoImportCsv"><i class="glyphicon glyphicon-info-sign"></i></a></h4> 
                                <%= form_tag import_cnae_path, multipart: true do %>
                                <%= file_field_tag :file %>
                                <%= submit_tag "Importar", class: 'btn btn-primary btn-xs'  %>
                                <% end %> 
                                <br>
                            </div>
                        </div>
                        <% if @cnaes.present? %>
                        <table class="table table-striped">
                            <thead>
                                <tr>
                                    <th>#</th>
                                    <th>Tipo Transação</th>
                                    <th>Cartão</th>
                                    <th>CPF</th>
                                    <th>Valor</th>
                                    <th>Data</th>
                                    <th>Hora</th>
                                </tr>
                            </thead>
                            <tbody>
                                <% @cnaes.each do |c| %>
                                <tr>
                                    <td><%= c.id %></td>
                                    <td><%= c.tp_occurrence %></td>
                                    <td><%= c.card %></td>
                                    <td><%= c.cpf %></td>
                                    <td><%= c.value %></td>
                                    <td><%= c.dt_occurrence.strftime('%d/%m/%Y') %></td>
                                    <td><%= c.tm_occurrence.strftime('%H:%M:%S') %></td>
                                </tr>
                                <% end %>
                            </tbody>
                        </table>
                        <% end %>
                        <!-- /.box-header -->
                        <!-- form start -->
                    </div>
                </div>
            </div>
            <!-- /.box -->
        </div>

    </div>
</section>